// filepath: /E:/Diet-App/diet_app_mobile/lib/API/services/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['API_KEY']!,
    authDomain: dotenv.env['AUTH_DOMAIN']!,
    projectId: dotenv.env['PROJECT_ID']!,
    storageBucket: dotenv.env['STORAGE_BUCKET']!,
    messagingSenderId: dotenv.env['MESSAGING_SENDER_ID']!,
    appId: dotenv.env['APP_ID']!,
    measurementId: dotenv.env['MEASUREMENT_ID'],
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['API_KEY']!,
    authDomain: dotenv.env['AUTH_DOMAIN']!,
    projectId: dotenv.env['PROJECT_ID']!,
    storageBucket: dotenv.env['STORAGE_BUCKET']!,
    messagingSenderId: dotenv.env['MESSAGING_SENDER_ID']!,
    appId: dotenv.env['APP_ID']!,
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['API_KEY']!,
    authDomain: dotenv.env['AUTH_DOMAIN']!,
    projectId: dotenv.env['PROJECT_ID']!,
    storageBucket: dotenv.env['STORAGE_BUCKET']!,
    messagingSenderId: dotenv.env['MESSAGING_SENDER_ID']!,
    appId: dotenv.env['APP_ID']!,
    iosClientId: dotenv.env['IOS_CLIENT_ID']!,
    iosBundleId: dotenv.env['IOS_BUNDLE_ID']!,
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['API_KEY']!,
    authDomain: dotenv.env['AUTH_DOMAIN']!,
    projectId: dotenv.env['PROJECT_ID']!,
    storageBucket: dotenv.env['STORAGE_BUCKET']!,
    messagingSenderId: dotenv.env['MESSAGING_SENDER_ID']!,
    appId: dotenv.env['APP_ID']!,
    iosClientId: dotenv.env['IOS_CLIENT_ID']!,
    iosBundleId: dotenv.env['IOS_BUNDLE_ID']!,
  );
}